// <auto-generated />
using System;
using Customo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Customo.Api.Migrations
{
    [DbContext(typeof(CustomoDbContext))]
    partial class CustomoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AllergenOrder", b =>
                {
                    b.Property<int>("AllergiesId")
                        .HasColumnType("int");

                    b.Property<int>("OrdersId")
                        .HasColumnType("int");

                    b.HasKey("AllergiesId", "OrdersId");

                    b.HasIndex("OrdersId");

                    b.ToTable("OrderAllergies", (string)null);
                });

            modelBuilder.Entity("Customo.Data.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Allergens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Peanuts"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tree nuts"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Milk"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Egg"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Wheat"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Soy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Shrimp"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Shellfish"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Sesame"
                        });
                });

            modelBuilder.Entity("Customo.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mains"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sides"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Drinks"
                        });
                });

            modelBuilder.Entity("Customo.Data.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Chicken Adobo",
                            Price = 150m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Pancit Canton",
                            Price = 120m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Kare-Kare",
                            Price = 250m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Pork Sisig",
                            Price = 180m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "Sinigang na Baboy",
                            Price = 200m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "Crispy Pata",
                            Price = 450m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "Lumpiang Shanghai",
                            Price = 100m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "Plain Rice",
                            Price = 30m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Halo-Halo",
                            Price = 110m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Name = "Leche Flan",
                            Price = 80m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Name = "Iced Tea",
                            Price = 60m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Name = "Mango Shake",
                            Price = 90m
                        });
                });

            modelBuilder.Entity("Customo.Data.MenuItemOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceDelta")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.ToTable("MenuItemOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MenuItemId = 1,
                            Name = "Extra rice",
                            PriceDelta = 20m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 2,
                            MenuItemId = 1,
                            Name = "Egg",
                            PriceDelta = 15m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 3,
                            MenuItemId = 1,
                            Name = "Steamed rice",
                            PriceDelta = 0m,
                            Type = "Swap"
                        },
                        new
                        {
                            Id = 4,
                            MenuItemId = 1,
                            Name = "Garlic rice",
                            PriceDelta = 10m,
                            Type = "Swap"
                        },
                        new
                        {
                            Id = 5,
                            MenuItemId = 2,
                            Name = "Extra veggies",
                            PriceDelta = 20m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 6,
                            MenuItemId = 3,
                            Name = "Extra bagoong",
                            PriceDelta = 10m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 7,
                            MenuItemId = 4,
                            Name = "Extra rice",
                            PriceDelta = 20m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 8,
                            MenuItemId = 4,
                            Name = "Egg",
                            PriceDelta = 15m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 9,
                            MenuItemId = 5,
                            Name = "Extra rice",
                            PriceDelta = 20m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 10,
                            MenuItemId = 6,
                            Name = "Extra sauce",
                            PriceDelta = 15m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 11,
                            MenuItemId = 7,
                            Name = "Sweet chili",
                            PriceDelta = 10m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 12,
                            MenuItemId = 9,
                            Name = "Ice cream",
                            PriceDelta = 30m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 13,
                            MenuItemId = 9,
                            Name = "Leche flan",
                            PriceDelta = 25m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 14,
                            MenuItemId = 11,
                            Name = "Regular",
                            PriceDelta = 0m,
                            Type = "Size"
                        },
                        new
                        {
                            Id = 15,
                            MenuItemId = 11,
                            Name = "Medium",
                            PriceDelta = 10m,
                            Type = "Size"
                        },
                        new
                        {
                            Id = 16,
                            MenuItemId = 11,
                            Name = "Large",
                            PriceDelta = 20m,
                            Type = "Size"
                        },
                        new
                        {
                            Id = 17,
                            MenuItemId = 12,
                            Name = "Regular",
                            PriceDelta = 0m,
                            Type = "Size"
                        },
                        new
                        {
                            Id = 18,
                            MenuItemId = 12,
                            Name = "Medium",
                            PriceDelta = 10m,
                            Type = "Size"
                        },
                        new
                        {
                            Id = 19,
                            MenuItemId = 12,
                            Name = "Large",
                            PriceDelta = 20m,
                            Type = "Size"
                        });
                });

            modelBuilder.Entity("Customo.Data.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Customo.Data.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasAllergyConflict")
                        .HasColumnType("bit");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Customo.Data.OrderItemOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceDelta")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.ToTable("OrderItemOptions");
                });

            modelBuilder.Entity("MenuItemAllergens", b =>
                {
                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("AllergenId")
                        .HasColumnType("int");

                    b.HasKey("MenuItemId", "AllergenId");

                    b.HasIndex("AllergenId");

                    b.ToTable("MenuItemAllergens");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            AllergenId = 6
                        },
                        new
                        {
                            MenuItemId = 2,
                            AllergenId = 5
                        },
                        new
                        {
                            MenuItemId = 2,
                            AllergenId = 4
                        },
                        new
                        {
                            MenuItemId = 2,
                            AllergenId = 8
                        },
                        new
                        {
                            MenuItemId = 3,
                            AllergenId = 1
                        },
                        new
                        {
                            MenuItemId = 3,
                            AllergenId = 8
                        },
                        new
                        {
                            MenuItemId = 4,
                            AllergenId = 4
                        },
                        new
                        {
                            MenuItemId = 4,
                            AllergenId = 6
                        },
                        new
                        {
                            MenuItemId = 5,
                            AllergenId = 7
                        },
                        new
                        {
                            MenuItemId = 6,
                            AllergenId = 6
                        },
                        new
                        {
                            MenuItemId = 7,
                            AllergenId = 5
                        },
                        new
                        {
                            MenuItemId = 7,
                            AllergenId = 4
                        },
                        new
                        {
                            MenuItemId = 9,
                            AllergenId = 3
                        },
                        new
                        {
                            MenuItemId = 9,
                            AllergenId = 1
                        },
                        new
                        {
                            MenuItemId = 10,
                            AllergenId = 3
                        },
                        new
                        {
                            MenuItemId = 10,
                            AllergenId = 4
                        },
                        new
                        {
                            MenuItemId = 12,
                            AllergenId = 3
                        });
                });

            modelBuilder.Entity("AllergenOrder", b =>
                {
                    b.HasOne("Customo.Data.Allergen", null)
                        .WithMany()
                        .HasForeignKey("AllergiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Customo.Data.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Customo.Data.MenuItem", b =>
                {
                    b.HasOne("Customo.Data.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Customo.Data.MenuItemOption", b =>
                {
                    b.HasOne("Customo.Data.MenuItem", "MenuItem")
                        .WithMany("Options")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("Customo.Data.OrderItem", b =>
                {
                    b.HasOne("Customo.Data.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Customo.Data.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Customo.Data.OrderItemOption", b =>
                {
                    b.HasOne("Customo.Data.OrderItem", "OrderItem")
                        .WithMany("Options")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("MenuItemAllergens", b =>
                {
                    b.HasOne("Customo.Data.Allergen", null)
                        .WithMany()
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Customo.Data.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Customo.Data.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("Customo.Data.MenuItem", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Customo.Data.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Customo.Data.OrderItem", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
