// <auto-generated />
using System;
using Customo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Customo.Api.Migrations
{
    [DbContext(typeof(CustomoDbContext))]
    partial class CustomoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AllergenOrder", b =>
                {
                    b.Property<int>("AllergiesId")
                        .HasColumnType("int");

                    b.Property<int>("OrdersId")
                        .HasColumnType("int");

                    b.HasKey("AllergiesId", "OrdersId");

                    b.HasIndex("OrdersId");

                    b.ToTable("OrderAllergies", (string)null);
                });

            modelBuilder.Entity("Customo.Data.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Allergens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Peanuts"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tree nuts"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Milk"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Egg"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Wheat"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Soy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Shrimp"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Shellfish"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Sesame"
                        });
                });

            modelBuilder.Entity("Customo.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mains"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sides"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Drinks"
                        });
                });

            modelBuilder.Entity("Customo.Data.DiningTable", b =>
                {
                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("ClaimToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OccupiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Number");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Number = 1
                        },
                        new
                        {
                            Number = 2
                        },
                        new
                        {
                            Number = 3
                        },
                        new
                        {
                            Number = 4
                        },
                        new
                        {
                            Number = 5
                        },
                        new
                        {
                            Number = 6
                        },
                        new
                        {
                            Number = 7
                        },
                        new
                        {
                            Number = 8
                        },
                        new
                        {
                            Number = 9
                        },
                        new
                        {
                            Number = 10
                        },
                        new
                        {
                            Number = 11
                        },
                        new
                        {
                            Number = 12
                        });
                });

            modelBuilder.Entity("Customo.Data.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AllergenId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AllergenId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 2,
                            AllergenId = 6,
                            Name = "Soy sauce"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vinegar"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Garlic"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bay leaf"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Black pepper"
                        },
                        new
                        {
                            Id = 7,
                            AllergenId = 5,
                            Name = "Canton noodles"
                        },
                        new
                        {
                            Id = 8,
                            AllergenId = 8,
                            Name = "Shrimp"
                        },
                        new
                        {
                            Id = 9,
                            AllergenId = 4,
                            Name = "Egg"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Cabbage"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Carrots"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Beef"
                        },
                        new
                        {
                            Id = 13,
                            AllergenId = 1,
                            Name = "Peanut sauce"
                        },
                        new
                        {
                            Id = 14,
                            AllergenId = 8,
                            Name = "Shrimp paste"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Eggplant"
                        },
                        new
                        {
                            Id = 16,
                            Name = "String beans"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Bok choy"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Pork"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Onions"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Chili"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Calamansi"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Tamarind broth"
                        },
                        new
                        {
                            Id = 23,
                            AllergenId = 7,
                            Name = "Fish sauce"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Radish"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Kangkong"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = 27,
                            AllergenId = 5,
                            Name = "Lumpia wrapper"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Rice"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Shaved ice"
                        },
                        new
                        {
                            Id = 30,
                            AllergenId = 3,
                            Name = "Milk"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Sweet beans"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Banana"
                        },
                        new
                        {
                            Id = 33,
                            AllergenId = 1,
                            Name = "Peanut topping"
                        },
                        new
                        {
                            Id = 34,
                            AllergenId = 3,
                            Name = "Condensed milk"
                        },
                        new
                        {
                            Id = 35,
                            AllergenId = 4,
                            Name = "Egg yolks"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Caramel"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Tea"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Sugar syrup"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Ice"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Lemon"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Mango"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Sugar"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Pork leg"
                        });
                });

            modelBuilder.Entity("Customo.Data.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Chicken Adobo",
                            Price = 150m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Pancit Canton",
                            Price = 120m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Kare-Kare",
                            Price = 250m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Pork Sisig",
                            Price = 180m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "Sinigang na Baboy",
                            Price = 200m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "Crispy Pata",
                            Price = 450m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "Lumpiang Shanghai",
                            Price = 100m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "Plain Rice",
                            Price = 30m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Halo-Halo",
                            Price = 110m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Name = "Leche Flan",
                            Price = 80m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Name = "Iced Tea",
                            Price = 60m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Name = "Mango Shake",
                            Price = 90m
                        });
                });

            modelBuilder.Entity("Customo.Data.MenuItemIngredient", b =>
                {
                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRemovable")
                        .HasColumnType("bit");

                    b.HasKey("MenuItemId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("MenuItemIngredients");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            IngredientId = 1,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 1,
                            IngredientId = 2,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 1,
                            IngredientId = 3,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 1,
                            IngredientId = 4,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 1,
                            IngredientId = 5,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 1,
                            IngredientId = 6,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 2,
                            IngredientId = 7,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 2,
                            IngredientId = 1,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 2,
                            IngredientId = 8,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 2,
                            IngredientId = 9,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 2,
                            IngredientId = 10,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 2,
                            IngredientId = 11,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 2,
                            IngredientId = 4,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 3,
                            IngredientId = 12,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 3,
                            IngredientId = 13,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 3,
                            IngredientId = 14,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 3,
                            IngredientId = 15,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 3,
                            IngredientId = 16,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 3,
                            IngredientId = 17,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 4,
                            IngredientId = 18,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 4,
                            IngredientId = 2,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 4,
                            IngredientId = 9,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 4,
                            IngredientId = 19,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 4,
                            IngredientId = 20,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 4,
                            IngredientId = 21,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 5,
                            IngredientId = 18,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 5,
                            IngredientId = 22,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 5,
                            IngredientId = 23,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 5,
                            IngredientId = 24,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 5,
                            IngredientId = 25,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 5,
                            IngredientId = 26,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 6,
                            IngredientId = 43,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 6,
                            IngredientId = 2,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 6,
                            IngredientId = 4,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 7,
                            IngredientId = 18,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 7,
                            IngredientId = 27,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 7,
                            IngredientId = 9,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 7,
                            IngredientId = 11,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 7,
                            IngredientId = 19,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 8,
                            IngredientId = 28,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 9,
                            IngredientId = 29,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 9,
                            IngredientId = 30,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 9,
                            IngredientId = 31,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 9,
                            IngredientId = 32,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 9,
                            IngredientId = 33,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 10,
                            IngredientId = 35,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 10,
                            IngredientId = 34,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 10,
                            IngredientId = 36,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 11,
                            IngredientId = 37,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 11,
                            IngredientId = 38,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 11,
                            IngredientId = 39,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 11,
                            IngredientId = 40,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 12,
                            IngredientId = 41,
                            IsRemovable = false
                        },
                        new
                        {
                            MenuItemId = 12,
                            IngredientId = 30,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 12,
                            IngredientId = 39,
                            IsRemovable = true
                        },
                        new
                        {
                            MenuItemId = 12,
                            IngredientId = 42,
                            IsRemovable = true
                        });
                });

            modelBuilder.Entity("Customo.Data.MenuItemOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceDelta")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.ToTable("MenuItemOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MenuItemId = 1,
                            Name = "Extra rice",
                            PriceDelta = 20m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 2,
                            MenuItemId = 1,
                            Name = "Egg",
                            PriceDelta = 15m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 3,
                            MenuItemId = 1,
                            Name = "Steamed rice",
                            PriceDelta = 0m,
                            Type = "Swap"
                        },
                        new
                        {
                            Id = 4,
                            MenuItemId = 1,
                            Name = "Garlic rice",
                            PriceDelta = 10m,
                            Type = "Swap"
                        },
                        new
                        {
                            Id = 5,
                            MenuItemId = 2,
                            Name = "Extra veggies",
                            PriceDelta = 20m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 6,
                            MenuItemId = 3,
                            Name = "Extra bagoong",
                            PriceDelta = 10m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 7,
                            MenuItemId = 4,
                            Name = "Extra rice",
                            PriceDelta = 20m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 8,
                            MenuItemId = 4,
                            Name = "Egg",
                            PriceDelta = 15m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 9,
                            MenuItemId = 5,
                            Name = "Extra rice",
                            PriceDelta = 20m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 10,
                            MenuItemId = 6,
                            Name = "Extra sauce",
                            PriceDelta = 15m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 11,
                            MenuItemId = 7,
                            Name = "Sweet chili",
                            PriceDelta = 10m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 12,
                            MenuItemId = 9,
                            Name = "Ice cream",
                            PriceDelta = 30m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 13,
                            MenuItemId = 9,
                            Name = "Leche flan",
                            PriceDelta = 25m,
                            Type = "Extra"
                        },
                        new
                        {
                            Id = 14,
                            MenuItemId = 11,
                            Name = "Regular",
                            PriceDelta = 0m,
                            Type = "Size"
                        },
                        new
                        {
                            Id = 15,
                            MenuItemId = 11,
                            Name = "Medium",
                            PriceDelta = 10m,
                            Type = "Size"
                        },
                        new
                        {
                            Id = 16,
                            MenuItemId = 11,
                            Name = "Large",
                            PriceDelta = 20m,
                            Type = "Size"
                        },
                        new
                        {
                            Id = 17,
                            MenuItemId = 12,
                            Name = "Regular",
                            PriceDelta = 0m,
                            Type = "Size"
                        },
                        new
                        {
                            Id = 18,
                            MenuItemId = 12,
                            Name = "Medium",
                            PriceDelta = 10m,
                            Type = "Size"
                        },
                        new
                        {
                            Id = 19,
                            MenuItemId = 12,
                            Name = "Large",
                            PriceDelta = 20m,
                            Type = "Size"
                        });
                });

            modelBuilder.Entity("Customo.Data.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Customo.Data.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasAllergyConflict")
                        .HasColumnType("bit");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Customo.Data.OrderItemOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceDelta")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.ToTable("OrderItemOptions");
                });

            modelBuilder.Entity("AllergenOrder", b =>
                {
                    b.HasOne("Customo.Data.Allergen", null)
                        .WithMany()
                        .HasForeignKey("AllergiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Customo.Data.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Customo.Data.Ingredient", b =>
                {
                    b.HasOne("Customo.Data.Allergen", "Allergen")
                        .WithMany()
                        .HasForeignKey("AllergenId");

                    b.Navigation("Allergen");
                });

            modelBuilder.Entity("Customo.Data.MenuItem", b =>
                {
                    b.HasOne("Customo.Data.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Customo.Data.MenuItemIngredient", b =>
                {
                    b.HasOne("Customo.Data.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Customo.Data.MenuItem", "MenuItem")
                        .WithMany("Ingredients")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("Customo.Data.MenuItemOption", b =>
                {
                    b.HasOne("Customo.Data.MenuItem", "MenuItem")
                        .WithMany("Options")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("Customo.Data.OrderItem", b =>
                {
                    b.HasOne("Customo.Data.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Customo.Data.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Customo.Data.OrderItemOption", b =>
                {
                    b.HasOne("Customo.Data.OrderItem", "OrderItem")
                        .WithMany("Options")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("Customo.Data.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("Customo.Data.MenuItem", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("Customo.Data.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Customo.Data.OrderItem", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
